# Generated by Django 2.0.5 on 2018-10-19 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Rollno', models.CharField(max_length=10)),
                ('Pin', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.CharField(max_length=10)),
                ('Instrument', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Rollno', models.CharField(max_length=10)),
                ('First', models.CharField(max_length=25)),
                ('Last', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Time', models.CharField(default='time', max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Pin', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('Instrument', models.CharField(default='No Instrument Selected', max_length=30)),
            ],
        ),
    ]
