# Generated by Django 2.0.5 on 2018-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Rollno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='Rollno',
            field=models.CharField(max_length=10),
        ),
    ]
