# Generated by Django 2.0.5 on 2018-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180831_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Instrument',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='Rollno',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
